delay:
  # Включена ли функция анти-флуда
  enabled: true
  # Сделать ли право на обход. Право такое "LuckChat.delay.bypass"
  bypass: false
  # Задержка между сообщениями в секундах
  delay: 3
  # Сообщение, если игрок пишет в чат слишком часто
  message: "&cВы сможете написать сообщение через %delay% сек."

# Настройка запрета на слова
word:
  # Включена ли функция блокировки слова
  enabled: true

  # Сделать ли право на обход. Право такое "LuckChat.word.bypass"
  bypass: false

  # Фильтрация запрещенных слов
  # Если написать "п и д о р" или "п,и,д,о,р" или "яп,и,доР" засчитает как мат)
  # Но такие фразы, как "не спи до рассвета" будет считать как мат, ибо(капсом выделил) "не сПИ ДО РАСсвета"
  # Такие фразы нужно вписывать в whitelist
  # Вайтлист работает также круто, например, "Эй, не спи до рассвета" будет считать разрешенным или, "Не спи до рассвета, киса"
  restricted:
    - "Блять"
    - "Сука"
    - "Ебать"
    - "Хуй"
    - "Хуйня"
    - "Залупа"
    - "Пизда"
    - "Пиздец"
    - "Ахуеть"
    - "Пидор"
    - "Пидорас"

  # Тот самый вайтлист
  whitelist:
    - "Не спи до рассвета"

  # Сообщение, если игрок пишет в чат запрещенные слова
  message: "&cВы не можете писать в чат такие плохие слова :("

questions:
  # Включена ли функция авто-ответа на вопрос
  enabled: true

  # Сделать ли право на обход. Право такое "LuckChat.questions.bypass"
  bypass: false

  # Сами вопросы
  values:
    question1:
      # Вариации вопроса
      variants:
        - "Айпи"
        - "Какое айпи"
        - "Какое айпи сервера"

      # Ответ на вопрос
      answer: "&eАйпи: 127.0.0.1"

# Форматы чата для разных групп
# Право на использование цветовых кодов - LuckChat.chat.colors
chats:
  global:
    # Символ в начале сообщения
    symbol: "!"

    # Форматы чата для групп
    formats:
      default: "&7[&aГ&7] &fИгрок %name% &7-&f %message%"
      admin: "&7[&aГ&7] &cАдмин %name% &7-&f %message%"
  local:
    # Радиус в котором будет видно данное сообщение
    distance: 100
    # Форматы чата для групп
    formats:
      default: "&7[&eЛ&7] &fИгрок %name% &7- &f%message%"
      admin: "&7[&eЛ&7] &cАдмин %name% &7- &f%message%"
